# .github/workflows/deploy.yml
name: Deploy to AWS Test

on:
  workflow_dispatch:
  #push:
    #branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::903578657742:role/GitHubECRPushRole
          aws-region: us-east-1
      
      - name: Test AWS access
        run: aws sts get-caller-identity
