name: Using MakeAll Build and Push API Docker Image 

on:
  #push:
    #branches: [main]  # or your deployment branch
  workflow_dispatch:

jobs:
  build-and-push-makeall:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: LoginDocker
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Run make all
          run: make all
