name: mypullflow

on:
  
  pull_request:
    types: [opened, reopened]
    

jobs:
  buildpullflow:

    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4
    - name: testpull
      run: echo "This will run when pull request is open" 
      
    - id: env-setup1
      run: |
            {
              echo "env_token1=production1"
              echo "env_domain1=example.com1"
            } >> $GITHUB_OUTPUT

    - run: |
              
              echo '### Workflow variables' >> $GITHUB_STEP_SUMMARY
              echo '| Variable   | Value       |' >> $GITHUB_STEP_SUMMARY
              echo '| ---------- | ----------- |' >> $GITHUB_STEP_SUMMARY
              echo '| env_token  |  ${{ steps.env-setup1.outputs.env_token1 }}  |' >> $GITHUB_STEP_SUMMARY
              echo '| env_domain |  ${{ steps.env-setup1.outputs.env_domain1 }}|' >> $GITHUB_STEP_SUMMARY

           
    
    
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        #message: |
          #Test successful1 !
        #reactions: rocket           


        message: |
          _(execution **${{ github.run_id }}** / attempt **${{ github.run_attempt }}**)_  
        comment_tag: execution  

#this is a test comment