name: mypushflow

on:
  push:
    branches: [ "main" ]
  

jobs:
  buildpushflow:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: display msg
      run: echo "this will prrint msg on push" #&&  echo "name=value" >> $GITHUB_OUTPUT && echo $GITHUB_OUTPUT
      
    #- id: env-setup
      #run: |
        #{
         #echo "env_token=production"
          #echo "env_domain=example.com"
        #} >> $GITHUB_OUTPUT
    #- run: |
        #echo "${{ steps.env-setup.outputs.env_token }}"
        #echo "${{ steps.env-setup.outputs.env_domain }}"





    - id: env-setup1
      run: |
            {
              echo "env_token1=production1"
              echo "env_domain1=example.com1"
            } >> $GITHUB_OUTPUT

            {
              #echo "| env_token  |  ${{ steps.env-setup1.outputs.env_token1 }}  |"
              #echo " "
              echo "### Workflow variables"
              echo "| Variable   | Value       |"
              echo "| ---------- | ----------- |"
              echo '| env_token  |  ${{ steps.env-setup1.outputs.env_token1 }}  |'
              #echo `| env_domain |  ${{ steps.env-setup1.outputs.env_domain1 }}|`
              echo "${{ steps.env-setup1.outputs.env_domain1 }} hi" 
            } >> $GITHUB_STEP_SUMMARY
    - run: |
            echo "${{ steps.env-setup1.outputs.env_token1 }} checking"
            echo "${{ steps.env-setup1.outputs.env_domain1 }}"
