name: scheduleflow

on:
  schedule:
    - cron: '*/5 * * * *'
    
  

jobs:
  myschedule:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: testschedule
      run: echo "this is scheduled every 5 minutes"  && echo "::set-output name=foo::$BAR"  && echo "$BAR"  # add this line
